import { Component, OnInit } from '@angular/core';
import { Course } from './course';
import { CourseService } from './course.service';

@Component({
  selector: 'app-courses',
  templateUrl: './table.component.html',
  styleUrls: ['./table.component.css']
})
export class CoursesComponent implements OnInit {
  courses: Course[] = [];
  displayDialog: boolean = false;
  selectedCourse: Course | null = null;

  constructor(private courseService: CourseService) { }
  
  ngOnInit(): void {
    this.getCourses();
  }

  getCourses(): void {
    this.courseService.getCourses()
      .subscribe(courses => this.courses = courses);
  }

  showAddDialog(): void {
    
      this.selectedCourse = {
        id: 0,  // Assuming the ID is generated by the backend
        name: '',
        branch: '',
        description: '',
        credits: 0
      };
      this.displayDialog = true;
    }

  editCourse(course: Course): void {
    this.selectedCourse = { ...course }; // Copy the course to avoid mutating the original object
    this.displayDialog = true;
  }

  deleteCourse(id: number): void {
    this.courseService.deleteCourse(id)
      .subscribe(() => {
        this.courses = this.courses.filter(course => course.id !== id);
      });
  }

  closeDialog(): void {
    this.displayDialog = false;
    this.getCourses(); // Optionally refresh the course list after closing the dialog
  }
}
