import { Component, OnInit } from '@angular/core';
import { Professor } from './professor';
import { ProfessorService } from './professor.service';

@Component({
  selector: 'app-professors',
  templateUrl: './table.component.html',
  styleUrls: ['./table.component.css']
})
export class ProfessorsComponent implements OnInit {
  professors: Professor[] = [];
  displayDialog: boolean = false;
  selectedProfessor: Professor | null = null;

  constructor(private professorService: ProfessorService) { }
  
  ngOnInit(): void {
    this.getProfessors();
  }

  getProfessors(): void {
    this.professorService.getProfessors()
      .subscribe(professors => this.professors = professors);
  }

  showAddDialog(): void {
      this.selectedProfessor = {
        id: 0,  // Assuming the ID is generated by the backend
        name: '',
        email: '',
        department: ''
      };
      this.displayDialog = true;
  }

  editProfessor(professor: Professor): void {
    this.selectedProfessor = { ...professor }; // Copy the professor to avoid mutating the original object
    this.displayDialog = true;
  }

  deleteProfessor(id: number): void {
    this.professorService.deleteProfessor(id)
      .subscribe(() => {
        this.professors = this.professors.filter(professor => professor.id !== id);
      });
  }

  closeDialog(): void {
    this.displayDialog = false;
    this.getProfessors(); // Optionally refresh the professor list after closing the dialog
  }
}
