import { Component, OnInit } from '@angular/core';
import { Student } from './student';
import { StudentService } from './student.service';
import { ActivatedRoute } from '@angular/router';
import { NgxUiLoaderService } from 'ngx-ui-loader';
import { ToastrService } from 'ngx-toastr'; // Import ToastrService

@Component({
  selector: 'app-students',
  templateUrl: './table.component.html',
  styleUrls: ['./table.component.css']
})
export class StudentsComponent implements OnInit {
  students: Student[] = [];
  displayDialog: boolean = false;
  selectedStudent: Student | null = null;

  constructor(
    private studentService: StudentService, 
    private route: ActivatedRoute,
    private ngxLoader: NgxUiLoaderService,
    private toastr: ToastrService // Inject ToastrService
  ) { }
  
  ngOnInit(): void {
    this.route.data.subscribe(data => {
      this.students = data['students'];
    });
  }

  showAddDialog(): void {
    this.selectedStudent = {
      id: undefined,  // Assuming the ID is generated by the backend
      name: null,
      age: null,
      branch: null
    };
    this.displayDialog = true;
  }

  editStudent(student: Student): void {
    this.selectedStudent = { ...student }; // Copy the student to avoid mutating the original object
    this.displayDialog = true;
  }

  deleteStudent(id: number): void {
    this.ngxLoader.start();
    this.studentService.deleteStudent(id)
      .subscribe(
        () => {
          this.refreshStudents();
          this.toastr.success('Student deleted successfully'); // Success toast
        },
        error => {
          this.toastr.error('Failed to delete student'); // Error toast
        }
      );
  }

  closeDialog(): void {
    this.displayDialog = false;
    this.refreshStudents();
  }

  refreshStudents(): void {
    this.ngxLoader.start();
    this.studentService.getStudents().subscribe(
      students => {
        this.students = students;
        this.toastr.info('Student list updated'); // Info toast
        this.ngxLoader.stop();
      },
      error => {
        this.toastr.error('Failed to updated student list'); // Error toast
        this.ngxLoader.stop();
      }
    );
  }
}
