import { Component, OnInit } from '@angular/core';
import { Student } from './student';
import { StudentService } from './student.service';

@Component({
  selector: 'app-students',
  templateUrl: './table.component.html',
  styleUrls: ['./table.component.css']
})
export class StudentsComponent implements OnInit {
  students: Student[] = [];
  displayDialog: boolean = false;
  selectedStudent: Student | null = null;

  constructor(private studentService: StudentService) { }
  
  ngOnInit(): void {
    this.getStudents();
  }

  getStudents(): void {
    this.studentService.getStudents()
      .subscribe(students => this.students = students);
  }

  showAddDialog(): void {
    this.selectedStudent = {
      id: undefined,  // Assuming the ID is generated by the backend
      name: null,
      age: null,
      branch: null
    };
    this.displayDialog = true;
  }

  editStudent(student: Student): void {
    this.selectedStudent = { ...student }; // Copy the student to avoid mutating the original object
    this.displayDialog = true;
  }

  deleteStudent(id: number): void {
    this.studentService.deleteStudent(id)
      .subscribe(() => {
        this.students = this.students.filter(student => student.id !== id);
      });
  }

  closeDialog(): void {
    this.displayDialog = false;
    this.getStudents(); // Optionally refresh the student list after closing the dialog
  }
}
